# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f11fad51e67c3761cdffe0013f60bf3d7c671d415cf2b4748453336f1794a28869039a9addc2ddde75d8eb1deba79ec63ec80f6e3580bad34b3d55b99e88790

test:
  secret_key_base: b787706b306a5d0ed2dd1d796b02f133b315f28d5b21caa0d8edf4c8344472a10b984d60af7e6931bee24ab56081c2685f76b5ffc4818fd64677d5a9d72164bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
